### ISSUE TITLE
syntax error in UPDATE statements using TTL

### ISSUE THREAD

**Issue by shayangz** [websudos/phantom#371]
When using an UPDATE statement with a TTL option, we are generating queries like this

```
UPDATE table TTL 100, SET column = 'value' where key = 'value'
```

instead of the correct syntax 

```
UPDATE table USING TTL 100 SET column = 'value' where key = 'value'
```

This is resulting in a `com.datastax.driver.core.exceptions.SyntaxError` in 1.17.5. 

This issue doesn't exist in 1.12.2.

**Comment by alexflav23** [comment]
Hi @shayangz,

Thank you for reporting this, it will be fixed very shortly.

Regards.

**Comment by alexflav23** [comment]
This is now fixed in `1.17.7`.

**Comment by shayangz** [comment]
Thanks for jumping on this. 

But I just tested again with 1.17.7 and I still see the issue. It doesn't look like the changes actually made it into the build for some reason.

**Comment by alexflav23** [comment]
Hi @shayangz,

I've added tests to the build so I'd say reload sbt or something just to be sure. If you could please double check and I'll do the same.

Regards.

**Comment by shayangz** [comment]
Hi @alexflav23,

I tried again today deleting all cached older versions of phantom. I still hits that issue. Were you able to look on your side?

```
[info] Set current project to bluetiger (in build file:/home/shayan/bluetiger/)
[info] Updating {file:/home/shayan/bluetiger/}nosql...
[info] Resolving jline#jline;2.12.1 ...
[info] downloading https://dl.bintray.com/websudos/oss-releases/com/websudos/phantom-dsl_2.11/1.17.7/phantom-dsl_2.11-1.17.7.jar ...
[info] 	[SUCCESSFUL ] com.websudos#phantom-dsl_2.11;1.17.7!phantom-dsl_2.11.jar (931ms)
[info] downloading https://dl.bintray.com/websudos/oss-releases/com/websudos/phantom-connectors_2.11/1.17.7/phantom-connectors_2.11-1.17.7.jar ...
[info] 	[SUCCESSFUL ] com.websudos#phantom-connectors_2.11;1.17.7!phantom-connectors_2.11.jar (536ms)
[info] downloading https://dl.bintray.com/websudos/oss-releases/com/websudos/diesel-engine_2.11/0.2.2/diesel-engine_2.11-0.2.2.jar ...
[info] 	[SUCCESSFUL ] com.websudos#diesel-engine_2.11;0.2.2!diesel-engine_2.11.jar (440ms)
[info] Done updating.
```

Thanks

**Comment by shayangz** [comment]
Ok, I did some more digging. This works properly if my query is constructed as 

```
TABLE
  .update
  .where(CONDITION)
  .ttl(PERIOD)
```

but if you do

```
TABLE
  .update
  .ttl(PERIOD)
  .where(CONDITION)
```

it will generate the wrong syntax.

So, I have a workaround for this now, but I think it would be best to fix this part of the issue too.
